weights: /scratch/user/u.mm115921/yolov5_drone_detection/yolo7tiny/yolo_tiny_Venkat_May13.pt
cfg: /scratch/user/u.mm115921/yolov5_drone_detection/yolo7tiny/cfg/training/yolov7-tinyVenkatV2-2.2MB.yaml
data: /scratch/user/u.mm115921/yolov5_drone_detection/yolo7tiny/data/droneDataset.yaml
hyp: /scratch/user/u.mm115921/yolov5_drone_detection/yolo7tiny/data/hyp.scratch.tiny.yaml
epochs: 100
batch_size: 32
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: cpu
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 4
project: runs/train
entity: null
name: yolov7tinyMay16
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze:
- 0
v5_metric: false
world_size: 1
global_rank: -1
save_dir: runs/train/yolov7tinyMay16
total_batch_size: 32
